// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StatisticsModule.proto

package zsdn.protocol;

public final class StatisticsModuleProtocol {
  private StatisticsModuleProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ToOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StatisticsModule_Proto.To)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .StatisticsModule_Proto.FooBar foo = 1;</code>
     */
    boolean hasFoo();
    /**
     * <code>optional .StatisticsModule_Proto.FooBar foo = 1;</code>
     */
    zsdn.protocol.StatisticsModuleProtocol.FooBar getFoo();
    /**
     * <code>optional .StatisticsModule_Proto.FooBar foo = 1;</code>
     */
    zsdn.protocol.StatisticsModuleProtocol.FooBarOrBuilder getFooOrBuilder();
  }
  /**
   * Protobuf type {@code StatisticsModule_Proto.To}
   */
  public static final class To extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:StatisticsModule_Proto.To)
      ToOrBuilder {
    // Use To.newBuilder() to construct.
    private To(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private To(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final To defaultInstance;
    public static To getDefaultInstance() {
      return defaultInstance;
    }

    public To getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private To(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              zsdn.protocol.StatisticsModuleProtocol.FooBar.Builder subBuilder = null;
              if (toMsgCase_ == 1) {
                subBuilder = ((zsdn.protocol.StatisticsModuleProtocol.FooBar) toMsg_).toBuilder();
              }
              toMsg_ = input.readMessage(zsdn.protocol.StatisticsModuleProtocol.FooBar.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((zsdn.protocol.StatisticsModuleProtocol.FooBar) toMsg_);
                toMsg_ = subBuilder.buildPartial();
              }
              toMsgCase_ = 1;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zsdn.protocol.StatisticsModuleProtocol.internal_static_StatisticsModule_Proto_To_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zsdn.protocol.StatisticsModuleProtocol.internal_static_StatisticsModule_Proto_To_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zsdn.protocol.StatisticsModuleProtocol.To.class, zsdn.protocol.StatisticsModuleProtocol.To.Builder.class);
    }

    public static com.google.protobuf.Parser<To> PARSER =
        new com.google.protobuf.AbstractParser<To>() {
      public To parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new To(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<To> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    private int toMsgCase_ = 0;
    private java.lang.Object toMsg_;
    public enum ToMsgCase
        implements com.google.protobuf.Internal.EnumLite {
      FOO(1),
      TOMSG_NOT_SET(0);
      private int value = 0;
      private ToMsgCase(int value) {
        this.value = value;
      }
      public static ToMsgCase valueOf(int value) {
        switch (value) {
          case 1: return FOO;
          case 0: return TOMSG_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ToMsgCase
    getToMsgCase() {
      return ToMsgCase.valueOf(
          toMsgCase_);
    }

    public static final int FOO_FIELD_NUMBER = 1;
    /**
     * <code>optional .StatisticsModule_Proto.FooBar foo = 1;</code>
     */
    public boolean hasFoo() {
      return toMsgCase_ == 1;
    }
    /**
     * <code>optional .StatisticsModule_Proto.FooBar foo = 1;</code>
     */
    public zsdn.protocol.StatisticsModuleProtocol.FooBar getFoo() {
      if (toMsgCase_ == 1) {
         return (zsdn.protocol.StatisticsModuleProtocol.FooBar) toMsg_;
      }
      return zsdn.protocol.StatisticsModuleProtocol.FooBar.getDefaultInstance();
    }
    /**
     * <code>optional .StatisticsModule_Proto.FooBar foo = 1;</code>
     */
    public zsdn.protocol.StatisticsModuleProtocol.FooBarOrBuilder getFooOrBuilder() {
      if (toMsgCase_ == 1) {
         return (zsdn.protocol.StatisticsModuleProtocol.FooBar) toMsg_;
      }
      return zsdn.protocol.StatisticsModuleProtocol.FooBar.getDefaultInstance();
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (toMsgCase_ == 1) {
        output.writeMessage(1, (zsdn.protocol.StatisticsModuleProtocol.FooBar) toMsg_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (toMsgCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (zsdn.protocol.StatisticsModuleProtocol.FooBar) toMsg_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static zsdn.protocol.StatisticsModuleProtocol.To parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.To parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.To parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.To parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.To parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.To parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.To parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.To parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.To parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.To parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(zsdn.protocol.StatisticsModuleProtocol.To prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StatisticsModule_Proto.To}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StatisticsModule_Proto.To)
        zsdn.protocol.StatisticsModuleProtocol.ToOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zsdn.protocol.StatisticsModuleProtocol.internal_static_StatisticsModule_Proto_To_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zsdn.protocol.StatisticsModuleProtocol.internal_static_StatisticsModule_Proto_To_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zsdn.protocol.StatisticsModuleProtocol.To.class, zsdn.protocol.StatisticsModuleProtocol.To.Builder.class);
      }

      // Construct using zsdn.protocol.StatisticsModuleProtocol.To.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        toMsgCase_ = 0;
        toMsg_ = null;
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return zsdn.protocol.StatisticsModuleProtocol.internal_static_StatisticsModule_Proto_To_descriptor;
      }

      public zsdn.protocol.StatisticsModuleProtocol.To getDefaultInstanceForType() {
        return zsdn.protocol.StatisticsModuleProtocol.To.getDefaultInstance();
      }

      public zsdn.protocol.StatisticsModuleProtocol.To build() {
        zsdn.protocol.StatisticsModuleProtocol.To result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public zsdn.protocol.StatisticsModuleProtocol.To buildPartial() {
        zsdn.protocol.StatisticsModuleProtocol.To result = new zsdn.protocol.StatisticsModuleProtocol.To(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (toMsgCase_ == 1) {
          if (fooBuilder_ == null) {
            result.toMsg_ = toMsg_;
          } else {
            result.toMsg_ = fooBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.toMsgCase_ = toMsgCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof zsdn.protocol.StatisticsModuleProtocol.To) {
          return mergeFrom((zsdn.protocol.StatisticsModuleProtocol.To)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(zsdn.protocol.StatisticsModuleProtocol.To other) {
        if (other == zsdn.protocol.StatisticsModuleProtocol.To.getDefaultInstance()) return this;
        switch (other.getToMsgCase()) {
          case FOO: {
            mergeFoo(other.getFoo());
            break;
          }
          case TOMSG_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        zsdn.protocol.StatisticsModuleProtocol.To parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (zsdn.protocol.StatisticsModuleProtocol.To) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int toMsgCase_ = 0;
      private java.lang.Object toMsg_;
      public ToMsgCase
          getToMsgCase() {
        return ToMsgCase.valueOf(
            toMsgCase_);
      }

      public Builder clearToMsg() {
        toMsgCase_ = 0;
        toMsg_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilder<
          zsdn.protocol.StatisticsModuleProtocol.FooBar, zsdn.protocol.StatisticsModuleProtocol.FooBar.Builder, zsdn.protocol.StatisticsModuleProtocol.FooBarOrBuilder> fooBuilder_;
      /**
       * <code>optional .StatisticsModule_Proto.FooBar foo = 1;</code>
       */
      public boolean hasFoo() {
        return toMsgCase_ == 1;
      }
      /**
       * <code>optional .StatisticsModule_Proto.FooBar foo = 1;</code>
       */
      public zsdn.protocol.StatisticsModuleProtocol.FooBar getFoo() {
        if (fooBuilder_ == null) {
          if (toMsgCase_ == 1) {
            return (zsdn.protocol.StatisticsModuleProtocol.FooBar) toMsg_;
          }
          return zsdn.protocol.StatisticsModuleProtocol.FooBar.getDefaultInstance();
        } else {
          if (toMsgCase_ == 1) {
            return fooBuilder_.getMessage();
          }
          return zsdn.protocol.StatisticsModuleProtocol.FooBar.getDefaultInstance();
        }
      }
      /**
       * <code>optional .StatisticsModule_Proto.FooBar foo = 1;</code>
       */
      public Builder setFoo(zsdn.protocol.StatisticsModuleProtocol.FooBar value) {
        if (fooBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          toMsg_ = value;
          onChanged();
        } else {
          fooBuilder_.setMessage(value);
        }
        toMsgCase_ = 1;
        return this;
      }
      /**
       * <code>optional .StatisticsModule_Proto.FooBar foo = 1;</code>
       */
      public Builder setFoo(
          zsdn.protocol.StatisticsModuleProtocol.FooBar.Builder builderForValue) {
        if (fooBuilder_ == null) {
          toMsg_ = builderForValue.build();
          onChanged();
        } else {
          fooBuilder_.setMessage(builderForValue.build());
        }
        toMsgCase_ = 1;
        return this;
      }
      /**
       * <code>optional .StatisticsModule_Proto.FooBar foo = 1;</code>
       */
      public Builder mergeFoo(zsdn.protocol.StatisticsModuleProtocol.FooBar value) {
        if (fooBuilder_ == null) {
          if (toMsgCase_ == 1 &&
              toMsg_ != zsdn.protocol.StatisticsModuleProtocol.FooBar.getDefaultInstance()) {
            toMsg_ = zsdn.protocol.StatisticsModuleProtocol.FooBar.newBuilder((zsdn.protocol.StatisticsModuleProtocol.FooBar) toMsg_)
                .mergeFrom(value).buildPartial();
          } else {
            toMsg_ = value;
          }
          onChanged();
        } else {
          if (toMsgCase_ == 1) {
            fooBuilder_.mergeFrom(value);
          }
          fooBuilder_.setMessage(value);
        }
        toMsgCase_ = 1;
        return this;
      }
      /**
       * <code>optional .StatisticsModule_Proto.FooBar foo = 1;</code>
       */
      public Builder clearFoo() {
        if (fooBuilder_ == null) {
          if (toMsgCase_ == 1) {
            toMsgCase_ = 0;
            toMsg_ = null;
            onChanged();
          }
        } else {
          if (toMsgCase_ == 1) {
            toMsgCase_ = 0;
            toMsg_ = null;
          }
          fooBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .StatisticsModule_Proto.FooBar foo = 1;</code>
       */
      public zsdn.protocol.StatisticsModuleProtocol.FooBar.Builder getFooBuilder() {
        return getFooFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .StatisticsModule_Proto.FooBar foo = 1;</code>
       */
      public zsdn.protocol.StatisticsModuleProtocol.FooBarOrBuilder getFooOrBuilder() {
        if ((toMsgCase_ == 1) && (fooBuilder_ != null)) {
          return fooBuilder_.getMessageOrBuilder();
        } else {
          if (toMsgCase_ == 1) {
            return (zsdn.protocol.StatisticsModuleProtocol.FooBar) toMsg_;
          }
          return zsdn.protocol.StatisticsModuleProtocol.FooBar.getDefaultInstance();
        }
      }
      /**
       * <code>optional .StatisticsModule_Proto.FooBar foo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          zsdn.protocol.StatisticsModuleProtocol.FooBar, zsdn.protocol.StatisticsModuleProtocol.FooBar.Builder, zsdn.protocol.StatisticsModuleProtocol.FooBarOrBuilder> 
          getFooFieldBuilder() {
        if (fooBuilder_ == null) {
          if (!(toMsgCase_ == 1)) {
            toMsg_ = zsdn.protocol.StatisticsModuleProtocol.FooBar.getDefaultInstance();
          }
          fooBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              zsdn.protocol.StatisticsModuleProtocol.FooBar, zsdn.protocol.StatisticsModuleProtocol.FooBar.Builder, zsdn.protocol.StatisticsModuleProtocol.FooBarOrBuilder>(
                  (zsdn.protocol.StatisticsModuleProtocol.FooBar) toMsg_,
                  getParentForChildren(),
                  isClean());
          toMsg_ = null;
        }
        toMsgCase_ = 1;
        return fooBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:StatisticsModule_Proto.To)
    }

    static {
      defaultInstance = new To(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:StatisticsModule_Proto.To)
  }

  public interface FromOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StatisticsModule_Proto.From)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .StatisticsModule_Proto.FooBar bar = 1;</code>
     */
    boolean hasBar();
    /**
     * <code>optional .StatisticsModule_Proto.FooBar bar = 1;</code>
     */
    zsdn.protocol.StatisticsModuleProtocol.FooBar getBar();
    /**
     * <code>optional .StatisticsModule_Proto.FooBar bar = 1;</code>
     */
    zsdn.protocol.StatisticsModuleProtocol.FooBarOrBuilder getBarOrBuilder();
  }
  /**
   * Protobuf type {@code StatisticsModule_Proto.From}
   */
  public static final class From extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:StatisticsModule_Proto.From)
      FromOrBuilder {
    // Use From.newBuilder() to construct.
    private From(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private From(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final From defaultInstance;
    public static From getDefaultInstance() {
      return defaultInstance;
    }

    public From getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private From(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              zsdn.protocol.StatisticsModuleProtocol.FooBar.Builder subBuilder = null;
              if (fromMsgCase_ == 1) {
                subBuilder = ((zsdn.protocol.StatisticsModuleProtocol.FooBar) fromMsg_).toBuilder();
              }
              fromMsg_ = input.readMessage(zsdn.protocol.StatisticsModuleProtocol.FooBar.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((zsdn.protocol.StatisticsModuleProtocol.FooBar) fromMsg_);
                fromMsg_ = subBuilder.buildPartial();
              }
              fromMsgCase_ = 1;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zsdn.protocol.StatisticsModuleProtocol.internal_static_StatisticsModule_Proto_From_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zsdn.protocol.StatisticsModuleProtocol.internal_static_StatisticsModule_Proto_From_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zsdn.protocol.StatisticsModuleProtocol.From.class, zsdn.protocol.StatisticsModuleProtocol.From.Builder.class);
    }

    public static com.google.protobuf.Parser<From> PARSER =
        new com.google.protobuf.AbstractParser<From>() {
      public From parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new From(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<From> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    private int fromMsgCase_ = 0;
    private java.lang.Object fromMsg_;
    public enum FromMsgCase
        implements com.google.protobuf.Internal.EnumLite {
      BAR(1),
      FROMMSG_NOT_SET(0);
      private int value = 0;
      private FromMsgCase(int value) {
        this.value = value;
      }
      public static FromMsgCase valueOf(int value) {
        switch (value) {
          case 1: return BAR;
          case 0: return FROMMSG_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public FromMsgCase
    getFromMsgCase() {
      return FromMsgCase.valueOf(
          fromMsgCase_);
    }

    public static final int BAR_FIELD_NUMBER = 1;
    /**
     * <code>optional .StatisticsModule_Proto.FooBar bar = 1;</code>
     */
    public boolean hasBar() {
      return fromMsgCase_ == 1;
    }
    /**
     * <code>optional .StatisticsModule_Proto.FooBar bar = 1;</code>
     */
    public zsdn.protocol.StatisticsModuleProtocol.FooBar getBar() {
      if (fromMsgCase_ == 1) {
         return (zsdn.protocol.StatisticsModuleProtocol.FooBar) fromMsg_;
      }
      return zsdn.protocol.StatisticsModuleProtocol.FooBar.getDefaultInstance();
    }
    /**
     * <code>optional .StatisticsModule_Proto.FooBar bar = 1;</code>
     */
    public zsdn.protocol.StatisticsModuleProtocol.FooBarOrBuilder getBarOrBuilder() {
      if (fromMsgCase_ == 1) {
         return (zsdn.protocol.StatisticsModuleProtocol.FooBar) fromMsg_;
      }
      return zsdn.protocol.StatisticsModuleProtocol.FooBar.getDefaultInstance();
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (fromMsgCase_ == 1) {
        output.writeMessage(1, (zsdn.protocol.StatisticsModuleProtocol.FooBar) fromMsg_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (fromMsgCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (zsdn.protocol.StatisticsModuleProtocol.FooBar) fromMsg_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static zsdn.protocol.StatisticsModuleProtocol.From parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.From parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.From parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.From parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.From parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.From parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.From parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.From parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.From parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.From parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(zsdn.protocol.StatisticsModuleProtocol.From prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StatisticsModule_Proto.From}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StatisticsModule_Proto.From)
        zsdn.protocol.StatisticsModuleProtocol.FromOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zsdn.protocol.StatisticsModuleProtocol.internal_static_StatisticsModule_Proto_From_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zsdn.protocol.StatisticsModuleProtocol.internal_static_StatisticsModule_Proto_From_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zsdn.protocol.StatisticsModuleProtocol.From.class, zsdn.protocol.StatisticsModuleProtocol.From.Builder.class);
      }

      // Construct using zsdn.protocol.StatisticsModuleProtocol.From.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fromMsgCase_ = 0;
        fromMsg_ = null;
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return zsdn.protocol.StatisticsModuleProtocol.internal_static_StatisticsModule_Proto_From_descriptor;
      }

      public zsdn.protocol.StatisticsModuleProtocol.From getDefaultInstanceForType() {
        return zsdn.protocol.StatisticsModuleProtocol.From.getDefaultInstance();
      }

      public zsdn.protocol.StatisticsModuleProtocol.From build() {
        zsdn.protocol.StatisticsModuleProtocol.From result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public zsdn.protocol.StatisticsModuleProtocol.From buildPartial() {
        zsdn.protocol.StatisticsModuleProtocol.From result = new zsdn.protocol.StatisticsModuleProtocol.From(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (fromMsgCase_ == 1) {
          if (barBuilder_ == null) {
            result.fromMsg_ = fromMsg_;
          } else {
            result.fromMsg_ = barBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.fromMsgCase_ = fromMsgCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof zsdn.protocol.StatisticsModuleProtocol.From) {
          return mergeFrom((zsdn.protocol.StatisticsModuleProtocol.From)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(zsdn.protocol.StatisticsModuleProtocol.From other) {
        if (other == zsdn.protocol.StatisticsModuleProtocol.From.getDefaultInstance()) return this;
        switch (other.getFromMsgCase()) {
          case BAR: {
            mergeBar(other.getBar());
            break;
          }
          case FROMMSG_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        zsdn.protocol.StatisticsModuleProtocol.From parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (zsdn.protocol.StatisticsModuleProtocol.From) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int fromMsgCase_ = 0;
      private java.lang.Object fromMsg_;
      public FromMsgCase
          getFromMsgCase() {
        return FromMsgCase.valueOf(
            fromMsgCase_);
      }

      public Builder clearFromMsg() {
        fromMsgCase_ = 0;
        fromMsg_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilder<
          zsdn.protocol.StatisticsModuleProtocol.FooBar, zsdn.protocol.StatisticsModuleProtocol.FooBar.Builder, zsdn.protocol.StatisticsModuleProtocol.FooBarOrBuilder> barBuilder_;
      /**
       * <code>optional .StatisticsModule_Proto.FooBar bar = 1;</code>
       */
      public boolean hasBar() {
        return fromMsgCase_ == 1;
      }
      /**
       * <code>optional .StatisticsModule_Proto.FooBar bar = 1;</code>
       */
      public zsdn.protocol.StatisticsModuleProtocol.FooBar getBar() {
        if (barBuilder_ == null) {
          if (fromMsgCase_ == 1) {
            return (zsdn.protocol.StatisticsModuleProtocol.FooBar) fromMsg_;
          }
          return zsdn.protocol.StatisticsModuleProtocol.FooBar.getDefaultInstance();
        } else {
          if (fromMsgCase_ == 1) {
            return barBuilder_.getMessage();
          }
          return zsdn.protocol.StatisticsModuleProtocol.FooBar.getDefaultInstance();
        }
      }
      /**
       * <code>optional .StatisticsModule_Proto.FooBar bar = 1;</code>
       */
      public Builder setBar(zsdn.protocol.StatisticsModuleProtocol.FooBar value) {
        if (barBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fromMsg_ = value;
          onChanged();
        } else {
          barBuilder_.setMessage(value);
        }
        fromMsgCase_ = 1;
        return this;
      }
      /**
       * <code>optional .StatisticsModule_Proto.FooBar bar = 1;</code>
       */
      public Builder setBar(
          zsdn.protocol.StatisticsModuleProtocol.FooBar.Builder builderForValue) {
        if (barBuilder_ == null) {
          fromMsg_ = builderForValue.build();
          onChanged();
        } else {
          barBuilder_.setMessage(builderForValue.build());
        }
        fromMsgCase_ = 1;
        return this;
      }
      /**
       * <code>optional .StatisticsModule_Proto.FooBar bar = 1;</code>
       */
      public Builder mergeBar(zsdn.protocol.StatisticsModuleProtocol.FooBar value) {
        if (barBuilder_ == null) {
          if (fromMsgCase_ == 1 &&
              fromMsg_ != zsdn.protocol.StatisticsModuleProtocol.FooBar.getDefaultInstance()) {
            fromMsg_ = zsdn.protocol.StatisticsModuleProtocol.FooBar.newBuilder((zsdn.protocol.StatisticsModuleProtocol.FooBar) fromMsg_)
                .mergeFrom(value).buildPartial();
          } else {
            fromMsg_ = value;
          }
          onChanged();
        } else {
          if (fromMsgCase_ == 1) {
            barBuilder_.mergeFrom(value);
          }
          barBuilder_.setMessage(value);
        }
        fromMsgCase_ = 1;
        return this;
      }
      /**
       * <code>optional .StatisticsModule_Proto.FooBar bar = 1;</code>
       */
      public Builder clearBar() {
        if (barBuilder_ == null) {
          if (fromMsgCase_ == 1) {
            fromMsgCase_ = 0;
            fromMsg_ = null;
            onChanged();
          }
        } else {
          if (fromMsgCase_ == 1) {
            fromMsgCase_ = 0;
            fromMsg_ = null;
          }
          barBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .StatisticsModule_Proto.FooBar bar = 1;</code>
       */
      public zsdn.protocol.StatisticsModuleProtocol.FooBar.Builder getBarBuilder() {
        return getBarFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .StatisticsModule_Proto.FooBar bar = 1;</code>
       */
      public zsdn.protocol.StatisticsModuleProtocol.FooBarOrBuilder getBarOrBuilder() {
        if ((fromMsgCase_ == 1) && (barBuilder_ != null)) {
          return barBuilder_.getMessageOrBuilder();
        } else {
          if (fromMsgCase_ == 1) {
            return (zsdn.protocol.StatisticsModuleProtocol.FooBar) fromMsg_;
          }
          return zsdn.protocol.StatisticsModuleProtocol.FooBar.getDefaultInstance();
        }
      }
      /**
       * <code>optional .StatisticsModule_Proto.FooBar bar = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          zsdn.protocol.StatisticsModuleProtocol.FooBar, zsdn.protocol.StatisticsModuleProtocol.FooBar.Builder, zsdn.protocol.StatisticsModuleProtocol.FooBarOrBuilder> 
          getBarFieldBuilder() {
        if (barBuilder_ == null) {
          if (!(fromMsgCase_ == 1)) {
            fromMsg_ = zsdn.protocol.StatisticsModuleProtocol.FooBar.getDefaultInstance();
          }
          barBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              zsdn.protocol.StatisticsModuleProtocol.FooBar, zsdn.protocol.StatisticsModuleProtocol.FooBar.Builder, zsdn.protocol.StatisticsModuleProtocol.FooBarOrBuilder>(
                  (zsdn.protocol.StatisticsModuleProtocol.FooBar) fromMsg_,
                  getParentForChildren(),
                  isClean());
          fromMsg_ = null;
        }
        fromMsgCase_ = 1;
        return barBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:StatisticsModule_Proto.From)
    }

    static {
      defaultInstance = new From(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:StatisticsModule_Proto.From)
  }

  public interface FooBarOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StatisticsModule_Proto.FooBar)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code StatisticsModule_Proto.FooBar}
   */
  public static final class FooBar extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:StatisticsModule_Proto.FooBar)
      FooBarOrBuilder {
    // Use FooBar.newBuilder() to construct.
    private FooBar(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FooBar(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FooBar defaultInstance;
    public static FooBar getDefaultInstance() {
      return defaultInstance;
    }

    public FooBar getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FooBar(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zsdn.protocol.StatisticsModuleProtocol.internal_static_StatisticsModule_Proto_FooBar_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zsdn.protocol.StatisticsModuleProtocol.internal_static_StatisticsModule_Proto_FooBar_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zsdn.protocol.StatisticsModuleProtocol.FooBar.class, zsdn.protocol.StatisticsModuleProtocol.FooBar.Builder.class);
    }

    public static com.google.protobuf.Parser<FooBar> PARSER =
        new com.google.protobuf.AbstractParser<FooBar>() {
      public FooBar parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FooBar(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FooBar> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static zsdn.protocol.StatisticsModuleProtocol.FooBar parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.FooBar parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.FooBar parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.FooBar parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.FooBar parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.FooBar parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.FooBar parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.FooBar parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.FooBar parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static zsdn.protocol.StatisticsModuleProtocol.FooBar parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(zsdn.protocol.StatisticsModuleProtocol.FooBar prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StatisticsModule_Proto.FooBar}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StatisticsModule_Proto.FooBar)
        zsdn.protocol.StatisticsModuleProtocol.FooBarOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zsdn.protocol.StatisticsModuleProtocol.internal_static_StatisticsModule_Proto_FooBar_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zsdn.protocol.StatisticsModuleProtocol.internal_static_StatisticsModule_Proto_FooBar_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zsdn.protocol.StatisticsModuleProtocol.FooBar.class, zsdn.protocol.StatisticsModuleProtocol.FooBar.Builder.class);
      }

      // Construct using zsdn.protocol.StatisticsModuleProtocol.FooBar.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return zsdn.protocol.StatisticsModuleProtocol.internal_static_StatisticsModule_Proto_FooBar_descriptor;
      }

      public zsdn.protocol.StatisticsModuleProtocol.FooBar getDefaultInstanceForType() {
        return zsdn.protocol.StatisticsModuleProtocol.FooBar.getDefaultInstance();
      }

      public zsdn.protocol.StatisticsModuleProtocol.FooBar build() {
        zsdn.protocol.StatisticsModuleProtocol.FooBar result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public zsdn.protocol.StatisticsModuleProtocol.FooBar buildPartial() {
        zsdn.protocol.StatisticsModuleProtocol.FooBar result = new zsdn.protocol.StatisticsModuleProtocol.FooBar(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof zsdn.protocol.StatisticsModuleProtocol.FooBar) {
          return mergeFrom((zsdn.protocol.StatisticsModuleProtocol.FooBar)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(zsdn.protocol.StatisticsModuleProtocol.FooBar other) {
        if (other == zsdn.protocol.StatisticsModuleProtocol.FooBar.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        zsdn.protocol.StatisticsModuleProtocol.FooBar parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (zsdn.protocol.StatisticsModuleProtocol.FooBar) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:StatisticsModule_Proto.FooBar)
    }

    static {
      defaultInstance = new FooBar(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:StatisticsModule_Proto.FooBar)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StatisticsModule_Proto_To_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StatisticsModule_Proto_To_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StatisticsModule_Proto_From_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StatisticsModule_Proto_From_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StatisticsModule_Proto_FooBar_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StatisticsModule_Proto_FooBar_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026StatisticsModule.proto\022\026StatisticsModu" +
      "le_Proto\"<\n\002To\022-\n\003foo\030\001 \001(\0132\036.Statistics" +
      "Module_Proto.FooBarH\000B\007\n\005ToMsg\"@\n\004From\022-" +
      "\n\003bar\030\001 \001(\0132\036.StatisticsModule_Proto.Foo" +
      "BarH\000B\t\n\007FromMsg\"\010\n\006FooBarB)\n\rzsdn.proto" +
      "colB\030StatisticsModuleProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_StatisticsModule_Proto_To_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StatisticsModule_Proto_To_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_StatisticsModule_Proto_To_descriptor,
        new java.lang.String[] { "Foo", "ToMsg", });
    internal_static_StatisticsModule_Proto_From_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_StatisticsModule_Proto_From_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_StatisticsModule_Proto_From_descriptor,
        new java.lang.String[] { "Bar", "FromMsg", });
    internal_static_StatisticsModule_Proto_FooBar_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_StatisticsModule_Proto_FooBar_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_StatisticsModule_Proto_FooBar_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
