// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SwitchAdapter.proto

package zsdn.protocol;

public final class SwitchAdapterProtocol {
  private SwitchAdapterProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SwitchAdapter_Proto.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .SwitchAdapter_Proto.Request.HandleOpenflowMessagesRequest handle_openflow_messages_request = 1;</code>
     */
    boolean hasHandleOpenflowMessagesRequest();
    /**
     * <code>optional .SwitchAdapter_Proto.Request.HandleOpenflowMessagesRequest handle_openflow_messages_request = 1;</code>
     */
    zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest getHandleOpenflowMessagesRequest();
    /**
     * <code>optional .SwitchAdapter_Proto.Request.HandleOpenflowMessagesRequest handle_openflow_messages_request = 1;</code>
     */
    zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequestOrBuilder getHandleOpenflowMessagesRequestOrBuilder();
  }
  /**
   * Protobuf type {@code SwitchAdapter_Proto.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:SwitchAdapter_Proto.Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }

    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest.Builder subBuilder = null;
              if (requestMsgCase_ == 1) {
                subBuilder = ((zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest) requestMsg_).toBuilder();
              }
              requestMsg_ = input.readMessage(zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest) requestMsg_);
                requestMsg_ = subBuilder.buildPartial();
              }
              requestMsgCase_ = 1;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zsdn.protocol.SwitchAdapterProtocol.internal_static_SwitchAdapter_Proto_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zsdn.protocol.SwitchAdapterProtocol.internal_static_SwitchAdapter_Proto_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zsdn.protocol.SwitchAdapterProtocol.Request.class, zsdn.protocol.SwitchAdapterProtocol.Request.Builder.class);
    }

    public static com.google.protobuf.Parser<Request> PARSER =
        new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public interface HandleOpenflowMessagesRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:SwitchAdapter_Proto.Request.HandleOpenflowMessagesRequest)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>repeated bytes open_flow_message = 1;</code>
       */
      java.util.List<com.google.protobuf.ByteString> getOpenFlowMessageList();
      /**
       * <code>repeated bytes open_flow_message = 1;</code>
       */
      int getOpenFlowMessageCount();
      /**
       * <code>repeated bytes open_flow_message = 1;</code>
       */
      com.google.protobuf.ByteString getOpenFlowMessage(int index);
    }
    /**
     * Protobuf type {@code SwitchAdapter_Proto.Request.HandleOpenflowMessagesRequest}
     */
    public static final class HandleOpenflowMessagesRequest extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:SwitchAdapter_Proto.Request.HandleOpenflowMessagesRequest)
        HandleOpenflowMessagesRequestOrBuilder {
      // Use HandleOpenflowMessagesRequest.newBuilder() to construct.
      private HandleOpenflowMessagesRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private HandleOpenflowMessagesRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final HandleOpenflowMessagesRequest defaultInstance;
      public static HandleOpenflowMessagesRequest getDefaultInstance() {
        return defaultInstance;
      }

      public HandleOpenflowMessagesRequest getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private HandleOpenflowMessagesRequest(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                  openFlowMessage_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                  mutable_bitField0_ |= 0x00000001;
                }
                openFlowMessage_.add(input.readBytes());
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
            openFlowMessage_ = java.util.Collections.unmodifiableList(openFlowMessage_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zsdn.protocol.SwitchAdapterProtocol.internal_static_SwitchAdapter_Proto_Request_HandleOpenflowMessagesRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zsdn.protocol.SwitchAdapterProtocol.internal_static_SwitchAdapter_Proto_Request_HandleOpenflowMessagesRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest.class, zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest.Builder.class);
      }

      public static com.google.protobuf.Parser<HandleOpenflowMessagesRequest> PARSER =
          new com.google.protobuf.AbstractParser<HandleOpenflowMessagesRequest>() {
        public HandleOpenflowMessagesRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new HandleOpenflowMessagesRequest(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<HandleOpenflowMessagesRequest> getParserForType() {
        return PARSER;
      }

      public static final int OPEN_FLOW_MESSAGE_FIELD_NUMBER = 1;
      private java.util.List<com.google.protobuf.ByteString> openFlowMessage_;
      /**
       * <code>repeated bytes open_flow_message = 1;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getOpenFlowMessageList() {
        return openFlowMessage_;
      }
      /**
       * <code>repeated bytes open_flow_message = 1;</code>
       */
      public int getOpenFlowMessageCount() {
        return openFlowMessage_.size();
      }
      /**
       * <code>repeated bytes open_flow_message = 1;</code>
       */
      public com.google.protobuf.ByteString getOpenFlowMessage(int index) {
        return openFlowMessage_.get(index);
      }

      private void initFields() {
        openFlowMessage_ = java.util.Collections.emptyList();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        for (int i = 0; i < openFlowMessage_.size(); i++) {
          output.writeBytes(1, openFlowMessage_.get(i));
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        {
          int dataSize = 0;
          for (int i = 0; i < openFlowMessage_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeBytesSizeNoTag(openFlowMessage_.get(i));
          }
          size += dataSize;
          size += 1 * getOpenFlowMessageList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code SwitchAdapter_Proto.Request.HandleOpenflowMessagesRequest}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:SwitchAdapter_Proto.Request.HandleOpenflowMessagesRequest)
          zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return zsdn.protocol.SwitchAdapterProtocol.internal_static_SwitchAdapter_Proto_Request_HandleOpenflowMessagesRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return zsdn.protocol.SwitchAdapterProtocol.internal_static_SwitchAdapter_Proto_Request_HandleOpenflowMessagesRequest_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest.class, zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest.Builder.class);
        }

        // Construct using zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          openFlowMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return zsdn.protocol.SwitchAdapterProtocol.internal_static_SwitchAdapter_Proto_Request_HandleOpenflowMessagesRequest_descriptor;
        }

        public zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest getDefaultInstanceForType() {
          return zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest.getDefaultInstance();
        }

        public zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest build() {
          zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest buildPartial() {
          zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest result = new zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest(this);
          int from_bitField0_ = bitField0_;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            openFlowMessage_ = java.util.Collections.unmodifiableList(openFlowMessage_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.openFlowMessage_ = openFlowMessage_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest) {
            return mergeFrom((zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest other) {
          if (other == zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest.getDefaultInstance()) return this;
          if (!other.openFlowMessage_.isEmpty()) {
            if (openFlowMessage_.isEmpty()) {
              openFlowMessage_ = other.openFlowMessage_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureOpenFlowMessageIsMutable();
              openFlowMessage_.addAll(other.openFlowMessage_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.util.List<com.google.protobuf.ByteString> openFlowMessage_ = java.util.Collections.emptyList();
        private void ensureOpenFlowMessageIsMutable() {
          if (!((bitField0_ & 0x00000001) == 0x00000001)) {
            openFlowMessage_ = new java.util.ArrayList<com.google.protobuf.ByteString>(openFlowMessage_);
            bitField0_ |= 0x00000001;
           }
        }
        /**
         * <code>repeated bytes open_flow_message = 1;</code>
         */
        public java.util.List<com.google.protobuf.ByteString>
            getOpenFlowMessageList() {
          return java.util.Collections.unmodifiableList(openFlowMessage_);
        }
        /**
         * <code>repeated bytes open_flow_message = 1;</code>
         */
        public int getOpenFlowMessageCount() {
          return openFlowMessage_.size();
        }
        /**
         * <code>repeated bytes open_flow_message = 1;</code>
         */
        public com.google.protobuf.ByteString getOpenFlowMessage(int index) {
          return openFlowMessage_.get(index);
        }
        /**
         * <code>repeated bytes open_flow_message = 1;</code>
         */
        public Builder setOpenFlowMessage(
            int index, com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureOpenFlowMessageIsMutable();
          openFlowMessage_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated bytes open_flow_message = 1;</code>
         */
        public Builder addOpenFlowMessage(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureOpenFlowMessageIsMutable();
          openFlowMessage_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated bytes open_flow_message = 1;</code>
         */
        public Builder addAllOpenFlowMessage(
            java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
          ensureOpenFlowMessageIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, openFlowMessage_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated bytes open_flow_message = 1;</code>
         */
        public Builder clearOpenFlowMessage() {
          openFlowMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:SwitchAdapter_Proto.Request.HandleOpenflowMessagesRequest)
      }

      static {
        defaultInstance = new HandleOpenflowMessagesRequest(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:SwitchAdapter_Proto.Request.HandleOpenflowMessagesRequest)
    }

    private int bitField0_;
    private int requestMsgCase_ = 0;
    private java.lang.Object requestMsg_;
    public enum RequestMsgCase
        implements com.google.protobuf.Internal.EnumLite {
      HANDLE_OPENFLOW_MESSAGES_REQUEST(1),
      REQUESTMSG_NOT_SET(0);
      private int value = 0;
      private RequestMsgCase(int value) {
        this.value = value;
      }
      public static RequestMsgCase valueOf(int value) {
        switch (value) {
          case 1: return HANDLE_OPENFLOW_MESSAGES_REQUEST;
          case 0: return REQUESTMSG_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public RequestMsgCase
    getRequestMsgCase() {
      return RequestMsgCase.valueOf(
          requestMsgCase_);
    }

    public static final int HANDLE_OPENFLOW_MESSAGES_REQUEST_FIELD_NUMBER = 1;
    /**
     * <code>optional .SwitchAdapter_Proto.Request.HandleOpenflowMessagesRequest handle_openflow_messages_request = 1;</code>
     */
    public boolean hasHandleOpenflowMessagesRequest() {
      return requestMsgCase_ == 1;
    }
    /**
     * <code>optional .SwitchAdapter_Proto.Request.HandleOpenflowMessagesRequest handle_openflow_messages_request = 1;</code>
     */
    public zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest getHandleOpenflowMessagesRequest() {
      if (requestMsgCase_ == 1) {
         return (zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest) requestMsg_;
      }
      return zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest.getDefaultInstance();
    }
    /**
     * <code>optional .SwitchAdapter_Proto.Request.HandleOpenflowMessagesRequest handle_openflow_messages_request = 1;</code>
     */
    public zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequestOrBuilder getHandleOpenflowMessagesRequestOrBuilder() {
      if (requestMsgCase_ == 1) {
         return (zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest) requestMsg_;
      }
      return zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest.getDefaultInstance();
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (requestMsgCase_ == 1) {
        output.writeMessage(1, (zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest) requestMsg_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (requestMsgCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest) requestMsg_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static zsdn.protocol.SwitchAdapterProtocol.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zsdn.protocol.SwitchAdapterProtocol.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zsdn.protocol.SwitchAdapterProtocol.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zsdn.protocol.SwitchAdapterProtocol.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zsdn.protocol.SwitchAdapterProtocol.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static zsdn.protocol.SwitchAdapterProtocol.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static zsdn.protocol.SwitchAdapterProtocol.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static zsdn.protocol.SwitchAdapterProtocol.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static zsdn.protocol.SwitchAdapterProtocol.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static zsdn.protocol.SwitchAdapterProtocol.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(zsdn.protocol.SwitchAdapterProtocol.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SwitchAdapter_Proto.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SwitchAdapter_Proto.Request)
        zsdn.protocol.SwitchAdapterProtocol.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zsdn.protocol.SwitchAdapterProtocol.internal_static_SwitchAdapter_Proto_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zsdn.protocol.SwitchAdapterProtocol.internal_static_SwitchAdapter_Proto_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zsdn.protocol.SwitchAdapterProtocol.Request.class, zsdn.protocol.SwitchAdapterProtocol.Request.Builder.class);
      }

      // Construct using zsdn.protocol.SwitchAdapterProtocol.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        requestMsgCase_ = 0;
        requestMsg_ = null;
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return zsdn.protocol.SwitchAdapterProtocol.internal_static_SwitchAdapter_Proto_Request_descriptor;
      }

      public zsdn.protocol.SwitchAdapterProtocol.Request getDefaultInstanceForType() {
        return zsdn.protocol.SwitchAdapterProtocol.Request.getDefaultInstance();
      }

      public zsdn.protocol.SwitchAdapterProtocol.Request build() {
        zsdn.protocol.SwitchAdapterProtocol.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public zsdn.protocol.SwitchAdapterProtocol.Request buildPartial() {
        zsdn.protocol.SwitchAdapterProtocol.Request result = new zsdn.protocol.SwitchAdapterProtocol.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (requestMsgCase_ == 1) {
          if (handleOpenflowMessagesRequestBuilder_ == null) {
            result.requestMsg_ = requestMsg_;
          } else {
            result.requestMsg_ = handleOpenflowMessagesRequestBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.requestMsgCase_ = requestMsgCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof zsdn.protocol.SwitchAdapterProtocol.Request) {
          return mergeFrom((zsdn.protocol.SwitchAdapterProtocol.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(zsdn.protocol.SwitchAdapterProtocol.Request other) {
        if (other == zsdn.protocol.SwitchAdapterProtocol.Request.getDefaultInstance()) return this;
        switch (other.getRequestMsgCase()) {
          case HANDLE_OPENFLOW_MESSAGES_REQUEST: {
            mergeHandleOpenflowMessagesRequest(other.getHandleOpenflowMessagesRequest());
            break;
          }
          case REQUESTMSG_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        zsdn.protocol.SwitchAdapterProtocol.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (zsdn.protocol.SwitchAdapterProtocol.Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int requestMsgCase_ = 0;
      private java.lang.Object requestMsg_;
      public RequestMsgCase
          getRequestMsgCase() {
        return RequestMsgCase.valueOf(
            requestMsgCase_);
      }

      public Builder clearRequestMsg() {
        requestMsgCase_ = 0;
        requestMsg_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilder<
          zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest, zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest.Builder, zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequestOrBuilder> handleOpenflowMessagesRequestBuilder_;
      /**
       * <code>optional .SwitchAdapter_Proto.Request.HandleOpenflowMessagesRequest handle_openflow_messages_request = 1;</code>
       */
      public boolean hasHandleOpenflowMessagesRequest() {
        return requestMsgCase_ == 1;
      }
      /**
       * <code>optional .SwitchAdapter_Proto.Request.HandleOpenflowMessagesRequest handle_openflow_messages_request = 1;</code>
       */
      public zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest getHandleOpenflowMessagesRequest() {
        if (handleOpenflowMessagesRequestBuilder_ == null) {
          if (requestMsgCase_ == 1) {
            return (zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest) requestMsg_;
          }
          return zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest.getDefaultInstance();
        } else {
          if (requestMsgCase_ == 1) {
            return handleOpenflowMessagesRequestBuilder_.getMessage();
          }
          return zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest.getDefaultInstance();
        }
      }
      /**
       * <code>optional .SwitchAdapter_Proto.Request.HandleOpenflowMessagesRequest handle_openflow_messages_request = 1;</code>
       */
      public Builder setHandleOpenflowMessagesRequest(zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest value) {
        if (handleOpenflowMessagesRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          requestMsg_ = value;
          onChanged();
        } else {
          handleOpenflowMessagesRequestBuilder_.setMessage(value);
        }
        requestMsgCase_ = 1;
        return this;
      }
      /**
       * <code>optional .SwitchAdapter_Proto.Request.HandleOpenflowMessagesRequest handle_openflow_messages_request = 1;</code>
       */
      public Builder setHandleOpenflowMessagesRequest(
          zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest.Builder builderForValue) {
        if (handleOpenflowMessagesRequestBuilder_ == null) {
          requestMsg_ = builderForValue.build();
          onChanged();
        } else {
          handleOpenflowMessagesRequestBuilder_.setMessage(builderForValue.build());
        }
        requestMsgCase_ = 1;
        return this;
      }
      /**
       * <code>optional .SwitchAdapter_Proto.Request.HandleOpenflowMessagesRequest handle_openflow_messages_request = 1;</code>
       */
      public Builder mergeHandleOpenflowMessagesRequest(zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest value) {
        if (handleOpenflowMessagesRequestBuilder_ == null) {
          if (requestMsgCase_ == 1 &&
              requestMsg_ != zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest.getDefaultInstance()) {
            requestMsg_ = zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest.newBuilder((zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest) requestMsg_)
                .mergeFrom(value).buildPartial();
          } else {
            requestMsg_ = value;
          }
          onChanged();
        } else {
          if (requestMsgCase_ == 1) {
            handleOpenflowMessagesRequestBuilder_.mergeFrom(value);
          }
          handleOpenflowMessagesRequestBuilder_.setMessage(value);
        }
        requestMsgCase_ = 1;
        return this;
      }
      /**
       * <code>optional .SwitchAdapter_Proto.Request.HandleOpenflowMessagesRequest handle_openflow_messages_request = 1;</code>
       */
      public Builder clearHandleOpenflowMessagesRequest() {
        if (handleOpenflowMessagesRequestBuilder_ == null) {
          if (requestMsgCase_ == 1) {
            requestMsgCase_ = 0;
            requestMsg_ = null;
            onChanged();
          }
        } else {
          if (requestMsgCase_ == 1) {
            requestMsgCase_ = 0;
            requestMsg_ = null;
          }
          handleOpenflowMessagesRequestBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .SwitchAdapter_Proto.Request.HandleOpenflowMessagesRequest handle_openflow_messages_request = 1;</code>
       */
      public zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest.Builder getHandleOpenflowMessagesRequestBuilder() {
        return getHandleOpenflowMessagesRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .SwitchAdapter_Proto.Request.HandleOpenflowMessagesRequest handle_openflow_messages_request = 1;</code>
       */
      public zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequestOrBuilder getHandleOpenflowMessagesRequestOrBuilder() {
        if ((requestMsgCase_ == 1) && (handleOpenflowMessagesRequestBuilder_ != null)) {
          return handleOpenflowMessagesRequestBuilder_.getMessageOrBuilder();
        } else {
          if (requestMsgCase_ == 1) {
            return (zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest) requestMsg_;
          }
          return zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest.getDefaultInstance();
        }
      }
      /**
       * <code>optional .SwitchAdapter_Proto.Request.HandleOpenflowMessagesRequest handle_openflow_messages_request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest, zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest.Builder, zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequestOrBuilder> 
          getHandleOpenflowMessagesRequestFieldBuilder() {
        if (handleOpenflowMessagesRequestBuilder_ == null) {
          if (!(requestMsgCase_ == 1)) {
            requestMsg_ = zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest.getDefaultInstance();
          }
          handleOpenflowMessagesRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest, zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest.Builder, zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequestOrBuilder>(
                  (zsdn.protocol.SwitchAdapterProtocol.Request.HandleOpenflowMessagesRequest) requestMsg_,
                  getParentForChildren(),
                  isClean());
          requestMsg_ = null;
        }
        requestMsgCase_ = 1;
        return handleOpenflowMessagesRequestBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:SwitchAdapter_Proto.Request)
    }

    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SwitchAdapter_Proto.Request)
  }

  public interface ReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SwitchAdapter_Proto.Reply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .SwitchAdapter_Proto.Reply.HandleOpenflowMessagesReply handle_openflow_messages_reply = 1;</code>
     */
    boolean hasHandleOpenflowMessagesReply();
    /**
     * <code>optional .SwitchAdapter_Proto.Reply.HandleOpenflowMessagesReply handle_openflow_messages_reply = 1;</code>
     */
    zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply getHandleOpenflowMessagesReply();
    /**
     * <code>optional .SwitchAdapter_Proto.Reply.HandleOpenflowMessagesReply handle_openflow_messages_reply = 1;</code>
     */
    zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReplyOrBuilder getHandleOpenflowMessagesReplyOrBuilder();
  }
  /**
   * Protobuf type {@code SwitchAdapter_Proto.Reply}
   */
  public static final class Reply extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:SwitchAdapter_Proto.Reply)
      ReplyOrBuilder {
    // Use Reply.newBuilder() to construct.
    private Reply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Reply(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Reply defaultInstance;
    public static Reply getDefaultInstance() {
      return defaultInstance;
    }

    public Reply getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Reply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply.Builder subBuilder = null;
              if (replyMsgCase_ == 1) {
                subBuilder = ((zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply) replyMsg_).toBuilder();
              }
              replyMsg_ = input.readMessage(zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply) replyMsg_);
                replyMsg_ = subBuilder.buildPartial();
              }
              replyMsgCase_ = 1;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zsdn.protocol.SwitchAdapterProtocol.internal_static_SwitchAdapter_Proto_Reply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zsdn.protocol.SwitchAdapterProtocol.internal_static_SwitchAdapter_Proto_Reply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zsdn.protocol.SwitchAdapterProtocol.Reply.class, zsdn.protocol.SwitchAdapterProtocol.Reply.Builder.class);
    }

    public static com.google.protobuf.Parser<Reply> PARSER =
        new com.google.protobuf.AbstractParser<Reply>() {
      public Reply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Reply(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Reply> getParserForType() {
      return PARSER;
    }

    public interface HandleOpenflowMessagesReplyOrBuilder extends
        // @@protoc_insertion_point(interface_extends:SwitchAdapter_Proto.Reply.HandleOpenflowMessagesReply)
        com.google.protobuf.MessageOrBuilder {
    }
    /**
     * Protobuf type {@code SwitchAdapter_Proto.Reply.HandleOpenflowMessagesReply}
     */
    public static final class HandleOpenflowMessagesReply extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:SwitchAdapter_Proto.Reply.HandleOpenflowMessagesReply)
        HandleOpenflowMessagesReplyOrBuilder {
      // Use HandleOpenflowMessagesReply.newBuilder() to construct.
      private HandleOpenflowMessagesReply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private HandleOpenflowMessagesReply(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final HandleOpenflowMessagesReply defaultInstance;
      public static HandleOpenflowMessagesReply getDefaultInstance() {
        return defaultInstance;
      }

      public HandleOpenflowMessagesReply getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private HandleOpenflowMessagesReply(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zsdn.protocol.SwitchAdapterProtocol.internal_static_SwitchAdapter_Proto_Reply_HandleOpenflowMessagesReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zsdn.protocol.SwitchAdapterProtocol.internal_static_SwitchAdapter_Proto_Reply_HandleOpenflowMessagesReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply.class, zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply.Builder.class);
      }

      public static com.google.protobuf.Parser<HandleOpenflowMessagesReply> PARSER =
          new com.google.protobuf.AbstractParser<HandleOpenflowMessagesReply>() {
        public HandleOpenflowMessagesReply parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new HandleOpenflowMessagesReply(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<HandleOpenflowMessagesReply> getParserForType() {
        return PARSER;
      }

      private void initFields() {
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code SwitchAdapter_Proto.Reply.HandleOpenflowMessagesReply}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:SwitchAdapter_Proto.Reply.HandleOpenflowMessagesReply)
          zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReplyOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return zsdn.protocol.SwitchAdapterProtocol.internal_static_SwitchAdapter_Proto_Reply_HandleOpenflowMessagesReply_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return zsdn.protocol.SwitchAdapterProtocol.internal_static_SwitchAdapter_Proto_Reply_HandleOpenflowMessagesReply_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply.class, zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply.Builder.class);
        }

        // Construct using zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return zsdn.protocol.SwitchAdapterProtocol.internal_static_SwitchAdapter_Proto_Reply_HandleOpenflowMessagesReply_descriptor;
        }

        public zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply getDefaultInstanceForType() {
          return zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply.getDefaultInstance();
        }

        public zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply build() {
          zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply buildPartial() {
          zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply result = new zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply(this);
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply) {
            return mergeFrom((zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply other) {
          if (other == zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply.getDefaultInstance()) return this;
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        // @@protoc_insertion_point(builder_scope:SwitchAdapter_Proto.Reply.HandleOpenflowMessagesReply)
      }

      static {
        defaultInstance = new HandleOpenflowMessagesReply(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:SwitchAdapter_Proto.Reply.HandleOpenflowMessagesReply)
    }

    private int bitField0_;
    private int replyMsgCase_ = 0;
    private java.lang.Object replyMsg_;
    public enum ReplyMsgCase
        implements com.google.protobuf.Internal.EnumLite {
      HANDLE_OPENFLOW_MESSAGES_REPLY(1),
      REPLYMSG_NOT_SET(0);
      private int value = 0;
      private ReplyMsgCase(int value) {
        this.value = value;
      }
      public static ReplyMsgCase valueOf(int value) {
        switch (value) {
          case 1: return HANDLE_OPENFLOW_MESSAGES_REPLY;
          case 0: return REPLYMSG_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ReplyMsgCase
    getReplyMsgCase() {
      return ReplyMsgCase.valueOf(
          replyMsgCase_);
    }

    public static final int HANDLE_OPENFLOW_MESSAGES_REPLY_FIELD_NUMBER = 1;
    /**
     * <code>optional .SwitchAdapter_Proto.Reply.HandleOpenflowMessagesReply handle_openflow_messages_reply = 1;</code>
     */
    public boolean hasHandleOpenflowMessagesReply() {
      return replyMsgCase_ == 1;
    }
    /**
     * <code>optional .SwitchAdapter_Proto.Reply.HandleOpenflowMessagesReply handle_openflow_messages_reply = 1;</code>
     */
    public zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply getHandleOpenflowMessagesReply() {
      if (replyMsgCase_ == 1) {
         return (zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply) replyMsg_;
      }
      return zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply.getDefaultInstance();
    }
    /**
     * <code>optional .SwitchAdapter_Proto.Reply.HandleOpenflowMessagesReply handle_openflow_messages_reply = 1;</code>
     */
    public zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReplyOrBuilder getHandleOpenflowMessagesReplyOrBuilder() {
      if (replyMsgCase_ == 1) {
         return (zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply) replyMsg_;
      }
      return zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply.getDefaultInstance();
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (replyMsgCase_ == 1) {
        output.writeMessage(1, (zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply) replyMsg_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (replyMsgCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply) replyMsg_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static zsdn.protocol.SwitchAdapterProtocol.Reply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zsdn.protocol.SwitchAdapterProtocol.Reply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zsdn.protocol.SwitchAdapterProtocol.Reply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zsdn.protocol.SwitchAdapterProtocol.Reply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zsdn.protocol.SwitchAdapterProtocol.Reply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static zsdn.protocol.SwitchAdapterProtocol.Reply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static zsdn.protocol.SwitchAdapterProtocol.Reply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static zsdn.protocol.SwitchAdapterProtocol.Reply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static zsdn.protocol.SwitchAdapterProtocol.Reply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static zsdn.protocol.SwitchAdapterProtocol.Reply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(zsdn.protocol.SwitchAdapterProtocol.Reply prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SwitchAdapter_Proto.Reply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SwitchAdapter_Proto.Reply)
        zsdn.protocol.SwitchAdapterProtocol.ReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zsdn.protocol.SwitchAdapterProtocol.internal_static_SwitchAdapter_Proto_Reply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zsdn.protocol.SwitchAdapterProtocol.internal_static_SwitchAdapter_Proto_Reply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zsdn.protocol.SwitchAdapterProtocol.Reply.class, zsdn.protocol.SwitchAdapterProtocol.Reply.Builder.class);
      }

      // Construct using zsdn.protocol.SwitchAdapterProtocol.Reply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        replyMsgCase_ = 0;
        replyMsg_ = null;
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return zsdn.protocol.SwitchAdapterProtocol.internal_static_SwitchAdapter_Proto_Reply_descriptor;
      }

      public zsdn.protocol.SwitchAdapterProtocol.Reply getDefaultInstanceForType() {
        return zsdn.protocol.SwitchAdapterProtocol.Reply.getDefaultInstance();
      }

      public zsdn.protocol.SwitchAdapterProtocol.Reply build() {
        zsdn.protocol.SwitchAdapterProtocol.Reply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public zsdn.protocol.SwitchAdapterProtocol.Reply buildPartial() {
        zsdn.protocol.SwitchAdapterProtocol.Reply result = new zsdn.protocol.SwitchAdapterProtocol.Reply(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (replyMsgCase_ == 1) {
          if (handleOpenflowMessagesReplyBuilder_ == null) {
            result.replyMsg_ = replyMsg_;
          } else {
            result.replyMsg_ = handleOpenflowMessagesReplyBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.replyMsgCase_ = replyMsgCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof zsdn.protocol.SwitchAdapterProtocol.Reply) {
          return mergeFrom((zsdn.protocol.SwitchAdapterProtocol.Reply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(zsdn.protocol.SwitchAdapterProtocol.Reply other) {
        if (other == zsdn.protocol.SwitchAdapterProtocol.Reply.getDefaultInstance()) return this;
        switch (other.getReplyMsgCase()) {
          case HANDLE_OPENFLOW_MESSAGES_REPLY: {
            mergeHandleOpenflowMessagesReply(other.getHandleOpenflowMessagesReply());
            break;
          }
          case REPLYMSG_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        zsdn.protocol.SwitchAdapterProtocol.Reply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (zsdn.protocol.SwitchAdapterProtocol.Reply) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int replyMsgCase_ = 0;
      private java.lang.Object replyMsg_;
      public ReplyMsgCase
          getReplyMsgCase() {
        return ReplyMsgCase.valueOf(
            replyMsgCase_);
      }

      public Builder clearReplyMsg() {
        replyMsgCase_ = 0;
        replyMsg_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilder<
          zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply, zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply.Builder, zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReplyOrBuilder> handleOpenflowMessagesReplyBuilder_;
      /**
       * <code>optional .SwitchAdapter_Proto.Reply.HandleOpenflowMessagesReply handle_openflow_messages_reply = 1;</code>
       */
      public boolean hasHandleOpenflowMessagesReply() {
        return replyMsgCase_ == 1;
      }
      /**
       * <code>optional .SwitchAdapter_Proto.Reply.HandleOpenflowMessagesReply handle_openflow_messages_reply = 1;</code>
       */
      public zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply getHandleOpenflowMessagesReply() {
        if (handleOpenflowMessagesReplyBuilder_ == null) {
          if (replyMsgCase_ == 1) {
            return (zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply) replyMsg_;
          }
          return zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply.getDefaultInstance();
        } else {
          if (replyMsgCase_ == 1) {
            return handleOpenflowMessagesReplyBuilder_.getMessage();
          }
          return zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply.getDefaultInstance();
        }
      }
      /**
       * <code>optional .SwitchAdapter_Proto.Reply.HandleOpenflowMessagesReply handle_openflow_messages_reply = 1;</code>
       */
      public Builder setHandleOpenflowMessagesReply(zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply value) {
        if (handleOpenflowMessagesReplyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          replyMsg_ = value;
          onChanged();
        } else {
          handleOpenflowMessagesReplyBuilder_.setMessage(value);
        }
        replyMsgCase_ = 1;
        return this;
      }
      /**
       * <code>optional .SwitchAdapter_Proto.Reply.HandleOpenflowMessagesReply handle_openflow_messages_reply = 1;</code>
       */
      public Builder setHandleOpenflowMessagesReply(
          zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply.Builder builderForValue) {
        if (handleOpenflowMessagesReplyBuilder_ == null) {
          replyMsg_ = builderForValue.build();
          onChanged();
        } else {
          handleOpenflowMessagesReplyBuilder_.setMessage(builderForValue.build());
        }
        replyMsgCase_ = 1;
        return this;
      }
      /**
       * <code>optional .SwitchAdapter_Proto.Reply.HandleOpenflowMessagesReply handle_openflow_messages_reply = 1;</code>
       */
      public Builder mergeHandleOpenflowMessagesReply(zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply value) {
        if (handleOpenflowMessagesReplyBuilder_ == null) {
          if (replyMsgCase_ == 1 &&
              replyMsg_ != zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply.getDefaultInstance()) {
            replyMsg_ = zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply.newBuilder((zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply) replyMsg_)
                .mergeFrom(value).buildPartial();
          } else {
            replyMsg_ = value;
          }
          onChanged();
        } else {
          if (replyMsgCase_ == 1) {
            handleOpenflowMessagesReplyBuilder_.mergeFrom(value);
          }
          handleOpenflowMessagesReplyBuilder_.setMessage(value);
        }
        replyMsgCase_ = 1;
        return this;
      }
      /**
       * <code>optional .SwitchAdapter_Proto.Reply.HandleOpenflowMessagesReply handle_openflow_messages_reply = 1;</code>
       */
      public Builder clearHandleOpenflowMessagesReply() {
        if (handleOpenflowMessagesReplyBuilder_ == null) {
          if (replyMsgCase_ == 1) {
            replyMsgCase_ = 0;
            replyMsg_ = null;
            onChanged();
          }
        } else {
          if (replyMsgCase_ == 1) {
            replyMsgCase_ = 0;
            replyMsg_ = null;
          }
          handleOpenflowMessagesReplyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .SwitchAdapter_Proto.Reply.HandleOpenflowMessagesReply handle_openflow_messages_reply = 1;</code>
       */
      public zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply.Builder getHandleOpenflowMessagesReplyBuilder() {
        return getHandleOpenflowMessagesReplyFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .SwitchAdapter_Proto.Reply.HandleOpenflowMessagesReply handle_openflow_messages_reply = 1;</code>
       */
      public zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReplyOrBuilder getHandleOpenflowMessagesReplyOrBuilder() {
        if ((replyMsgCase_ == 1) && (handleOpenflowMessagesReplyBuilder_ != null)) {
          return handleOpenflowMessagesReplyBuilder_.getMessageOrBuilder();
        } else {
          if (replyMsgCase_ == 1) {
            return (zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply) replyMsg_;
          }
          return zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply.getDefaultInstance();
        }
      }
      /**
       * <code>optional .SwitchAdapter_Proto.Reply.HandleOpenflowMessagesReply handle_openflow_messages_reply = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply, zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply.Builder, zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReplyOrBuilder> 
          getHandleOpenflowMessagesReplyFieldBuilder() {
        if (handleOpenflowMessagesReplyBuilder_ == null) {
          if (!(replyMsgCase_ == 1)) {
            replyMsg_ = zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply.getDefaultInstance();
          }
          handleOpenflowMessagesReplyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply, zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply.Builder, zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReplyOrBuilder>(
                  (zsdn.protocol.SwitchAdapterProtocol.Reply.HandleOpenflowMessagesReply) replyMsg_,
                  getParentForChildren(),
                  isClean());
          replyMsg_ = null;
        }
        replyMsgCase_ = 1;
        return handleOpenflowMessagesReplyBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:SwitchAdapter_Proto.Reply)
    }

    static {
      defaultInstance = new Reply(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SwitchAdapter_Proto.Reply)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SwitchAdapter_Proto_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SwitchAdapter_Proto_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SwitchAdapter_Proto_Request_HandleOpenflowMessagesRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SwitchAdapter_Proto_Request_HandleOpenflowMessagesRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SwitchAdapter_Proto_Reply_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SwitchAdapter_Proto_Reply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SwitchAdapter_Proto_Reply_HandleOpenflowMessagesReply_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SwitchAdapter_Proto_Reply_HandleOpenflowMessagesReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023SwitchAdapter.proto\022\023SwitchAdapter_Pro" +
      "to\"\273\001\n\007Request\022f\n handle_openflow_messag" +
      "es_request\030\001 \001(\0132:.SwitchAdapter_Proto.R" +
      "equest.HandleOpenflowMessagesRequestH\000\032:" +
      "\n\035HandleOpenflowMessagesRequest\022\031\n\021open_" +
      "flow_message\030\001 \003(\014B\014\n\nRequestMsg\"\224\001\n\005Rep" +
      "ly\022`\n\036handle_openflow_messages_reply\030\001 \001" +
      "(\01326.SwitchAdapter_Proto.Reply.HandleOpe" +
      "nflowMessagesReplyH\000\032\035\n\033HandleOpenflowMe" +
      "ssagesReplyB\n\n\010ReplyMsgB&\n\rzsdn.protocol",
      "B\025SwitchAdapterProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SwitchAdapter_Proto_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SwitchAdapter_Proto_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SwitchAdapter_Proto_Request_descriptor,
        new java.lang.String[] { "HandleOpenflowMessagesRequest", "RequestMsg", });
    internal_static_SwitchAdapter_Proto_Request_HandleOpenflowMessagesRequest_descriptor =
      internal_static_SwitchAdapter_Proto_Request_descriptor.getNestedTypes().get(0);
    internal_static_SwitchAdapter_Proto_Request_HandleOpenflowMessagesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SwitchAdapter_Proto_Request_HandleOpenflowMessagesRequest_descriptor,
        new java.lang.String[] { "OpenFlowMessage", });
    internal_static_SwitchAdapter_Proto_Reply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SwitchAdapter_Proto_Reply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SwitchAdapter_Proto_Reply_descriptor,
        new java.lang.String[] { "HandleOpenflowMessagesReply", "ReplyMsg", });
    internal_static_SwitchAdapter_Proto_Reply_HandleOpenflowMessagesReply_descriptor =
      internal_static_SwitchAdapter_Proto_Reply_descriptor.getNestedTypes().get(0);
    internal_static_SwitchAdapter_Proto_Reply_HandleOpenflowMessagesReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SwitchAdapter_Proto_Reply_HandleOpenflowMessagesReply_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
