package zsdn.topics;

import jmf.data.MessageType;
import jmf.data.builder.MessageTypeBuilder;

/**
 * Autogenerated Code. Changes here will be automatically overwritten.
 *
 * @author Andre Kutzleb
 */
public class StatisticsModuleTopics {

private static final byte  TOPIC_VAL__TO = (byte)0x01L;
private static final byte  TOPIC_VAL__FROM = (byte)0x02L;
private static final short TOPIC_VAL__FROM__STATISTICS_MODULE = (short)0x0001L;
private static final byte  TOPIC_VAL__FROM__STATISTICS_MODULE__STATISTIC_EVENT = (byte)0x00L;
private static final byte  TOPIC_VAL__FROM__STATISTICS_MODULE__STATISTIC_EVENT__ADDED = (byte)0x00L;
private static final byte  TOPIC_VAL__REQUEST = (byte)0x03L;
private static final byte  TOPIC_VAL__REPLY = (byte)0x04L;

public static class TO {
private final MessageTypeBuilder id;
public TO() {id = new MessageTypeBuilder(); id.appendMatch8((byte) TOPIC_VAL__TO); }
public TO(MessageTypeBuilder preallocatedBuilder) {id = preallocatedBuilder; id.appendMatch8((byte) TOPIC_VAL__TO); }
public MessageType build() {return id.build();}
public MessageTypeBuilder getBuilderBack() {return id;}
};

public static class FROM {
private final MessageTypeBuilder id;
public class STATISTICS_MODULE {
public class STATISTIC_EVENT {
public class ADDED {
private ADDED() {id.appendMatch8((byte) TOPIC_VAL__FROM__STATISTICS_MODULE__STATISTIC_EVENT__ADDED); }
public MessageType build() {return id.build();}
public MessageTypeBuilder getBuilderBack() {return id;}
};

private STATISTIC_EVENT() {id.appendMatch8((byte) TOPIC_VAL__FROM__STATISTICS_MODULE__STATISTIC_EVENT); }
public ADDED added() {return new ADDED();}
public MessageType build() {return id.build();}
public MessageTypeBuilder getBuilderBack() {return id;}
};

private STATISTICS_MODULE() {id.appendMatch16((short) TOPIC_VAL__FROM__STATISTICS_MODULE); }
public STATISTIC_EVENT statistic_event() {return new STATISTIC_EVENT();}
public MessageType build() {return id.build();}
public MessageTypeBuilder getBuilderBack() {return id;}
};

public FROM() {id = new MessageTypeBuilder(); id.appendMatch8((byte) TOPIC_VAL__FROM); }
public FROM(MessageTypeBuilder preallocatedBuilder) {id = preallocatedBuilder; id.appendMatch8((byte) TOPIC_VAL__FROM); }
public STATISTICS_MODULE statistics_module() {return new STATISTICS_MODULE();}
public MessageType build() {return id.build();}
public MessageTypeBuilder getBuilderBack() {return id;}
};

public static class REQUEST {
private final MessageTypeBuilder id;
public REQUEST() {id = new MessageTypeBuilder(); id.appendMatch8((byte) TOPIC_VAL__REQUEST); }
public REQUEST(MessageTypeBuilder preallocatedBuilder) {id = preallocatedBuilder; id.appendMatch8((byte) TOPIC_VAL__REQUEST); }
public MessageType build() {return id.build();}
public MessageTypeBuilder getBuilderBack() {return id;}
};

public static class REPLY {
private final MessageTypeBuilder id;
public REPLY() {id = new MessageTypeBuilder(); id.appendMatch8((byte) TOPIC_VAL__REPLY); }
public REPLY(MessageTypeBuilder preallocatedBuilder) {id = preallocatedBuilder; id.appendMatch8((byte) TOPIC_VAL__REPLY); }
public MessageType build() {return id.build();}
public MessageTypeBuilder getBuilderBack() {return id;}
};

};
