package zsdn.topics;

import jmf.data.MessageType;
import jmf.data.builder.MessageTypeBuilder;

/**
 * Autogenerated Code. Changes here will be automatically overwritten.
 *
 * @author Andre Kutzleb
 */
public class SwitchRegistryModuleTopics {

private static final byte  TOPIC_VAL__TO = (byte)0x01L;
private static final byte  TOPIC_VAL__FROM = (byte)0x02L;
private static final short TOPIC_VAL__FROM__SWITCH_REGISTRY_MODULE = (short)0x0001L;
private static final byte  TOPIC_VAL__FROM__SWITCH_REGISTRY_MODULE__SWITCH_EVENT = (byte)0x00L;
private static final byte  TOPIC_VAL__FROM__SWITCH_REGISTRY_MODULE__SWITCH_EVENT__ADDED = (byte)0x00L;
private static final byte  TOPIC_VAL__FROM__SWITCH_REGISTRY_MODULE__SWITCH_EVENT__REMOVED = (byte)0x01L;
private static final byte  TOPIC_VAL__FROM__SWITCH_REGISTRY_MODULE__SWITCH_EVENT__CHANGED = (byte)0x02L;
private static final byte  TOPIC_VAL__REQUEST = (byte)0x03L;
private static final short TOPIC_VAL__REQUEST__SWITCH_REGISTRY_MODULE = (short)0x0001L;
private static final byte  TOPIC_VAL__REQUEST__SWITCH_REGISTRY_MODULE__GET_ALL_SWITCHES = (byte)0x00L;
private static final byte  TOPIC_VAL__REQUEST__SWITCH_REGISTRY_MODULE__GET_SWITCH_BY_ID = (byte)0x01L;
private static final byte  TOPIC_VAL__REPLY = (byte)0x04L;
private static final short TOPIC_VAL__REPLY__SWITCH_REGISTRY_MODULE = (short)0x0001L;
private static final byte  TOPIC_VAL__REPLY__SWITCH_REGISTRY_MODULE__GET_ALL_SWITCHES = (byte)0x00L;
private static final byte  TOPIC_VAL__REPLY__SWITCH_REGISTRY_MODULE__GET_SWITCH_BY_ID = (byte)0x01L;

public static class TO {
private final MessageTypeBuilder id;
public TO() {id = new MessageTypeBuilder(); id.appendMatch8((byte) TOPIC_VAL__TO); }
public TO(MessageTypeBuilder preallocatedBuilder) {id = preallocatedBuilder; id.appendMatch8((byte) TOPIC_VAL__TO); }
public MessageType build() {return id.build();}
public MessageTypeBuilder getBuilderBack() {return id;}
};

public static class FROM {
private final MessageTypeBuilder id;
public class SWITCH_REGISTRY_MODULE {
public class SWITCH_EVENT {
public class ADDED {
private ADDED() {id.appendMatch8((byte) TOPIC_VAL__FROM__SWITCH_REGISTRY_MODULE__SWITCH_EVENT__ADDED); }
public MessageType build() {return id.build();}
public MessageTypeBuilder getBuilderBack() {return id;}
};

public class REMOVED {
private REMOVED() {id.appendMatch8((byte) TOPIC_VAL__FROM__SWITCH_REGISTRY_MODULE__SWITCH_EVENT__REMOVED); }
public MessageType build() {return id.build();}
public MessageTypeBuilder getBuilderBack() {return id;}
};

public class CHANGED {
private CHANGED() {id.appendMatch8((byte) TOPIC_VAL__FROM__SWITCH_REGISTRY_MODULE__SWITCH_EVENT__CHANGED); }
public MessageType build() {return id.build();}
public MessageTypeBuilder getBuilderBack() {return id;}
};

private SWITCH_EVENT() {id.appendMatch8((byte) TOPIC_VAL__FROM__SWITCH_REGISTRY_MODULE__SWITCH_EVENT); }
public ADDED added() {return new ADDED();}
public REMOVED removed() {return new REMOVED();}
public CHANGED changed() {return new CHANGED();}
public MessageType build() {return id.build();}
public MessageTypeBuilder getBuilderBack() {return id;}
};

private SWITCH_REGISTRY_MODULE() {id.appendMatch16((short) TOPIC_VAL__FROM__SWITCH_REGISTRY_MODULE); }
public SWITCH_EVENT switch_event() {return new SWITCH_EVENT();}
public MessageType build() {return id.build();}
public MessageTypeBuilder getBuilderBack() {return id;}
};

public FROM() {id = new MessageTypeBuilder(); id.appendMatch8((byte) TOPIC_VAL__FROM); }
public FROM(MessageTypeBuilder preallocatedBuilder) {id = preallocatedBuilder; id.appendMatch8((byte) TOPIC_VAL__FROM); }
public SWITCH_REGISTRY_MODULE switch_registry_module() {return new SWITCH_REGISTRY_MODULE();}
public MessageType build() {return id.build();}
public MessageTypeBuilder getBuilderBack() {return id;}
};

public static class REQUEST {
private final MessageTypeBuilder id;
public class SWITCH_REGISTRY_MODULE {
public class GET_ALL_SWITCHES {
private GET_ALL_SWITCHES() {id.appendMatch8((byte) TOPIC_VAL__REQUEST__SWITCH_REGISTRY_MODULE__GET_ALL_SWITCHES); }
public MessageType build() {return id.build();}
public MessageTypeBuilder getBuilderBack() {return id;}
};

public class GET_SWITCH_BY_ID {
private GET_SWITCH_BY_ID() {id.appendMatch8((byte) TOPIC_VAL__REQUEST__SWITCH_REGISTRY_MODULE__GET_SWITCH_BY_ID); }
public MessageType build() {return id.build();}
public MessageTypeBuilder getBuilderBack() {return id;}
};

private SWITCH_REGISTRY_MODULE() {id.appendMatch16((short) TOPIC_VAL__REQUEST__SWITCH_REGISTRY_MODULE); }
public GET_ALL_SWITCHES get_all_switches() {return new GET_ALL_SWITCHES();}
public GET_SWITCH_BY_ID get_switch_by_id() {return new GET_SWITCH_BY_ID();}
public MessageType build() {return id.build();}
public MessageTypeBuilder getBuilderBack() {return id;}
};

public REQUEST() {id = new MessageTypeBuilder(); id.appendMatch8((byte) TOPIC_VAL__REQUEST); }
public REQUEST(MessageTypeBuilder preallocatedBuilder) {id = preallocatedBuilder; id.appendMatch8((byte) TOPIC_VAL__REQUEST); }
public SWITCH_REGISTRY_MODULE switch_registry_module() {return new SWITCH_REGISTRY_MODULE();}
public MessageType build() {return id.build();}
public MessageTypeBuilder getBuilderBack() {return id;}
};

public static class REPLY {
private final MessageTypeBuilder id;
public class SWITCH_REGISTRY_MODULE {
public class GET_ALL_SWITCHES {
private GET_ALL_SWITCHES() {id.appendMatch8((byte) TOPIC_VAL__REPLY__SWITCH_REGISTRY_MODULE__GET_ALL_SWITCHES); }
public MessageType build() {return id.build();}
public MessageTypeBuilder getBuilderBack() {return id;}
};

public class GET_SWITCH_BY_ID {
private GET_SWITCH_BY_ID() {id.appendMatch8((byte) TOPIC_VAL__REPLY__SWITCH_REGISTRY_MODULE__GET_SWITCH_BY_ID); }
public MessageType build() {return id.build();}
public MessageTypeBuilder getBuilderBack() {return id;}
};

private SWITCH_REGISTRY_MODULE() {id.appendMatch16((short) TOPIC_VAL__REPLY__SWITCH_REGISTRY_MODULE); }
public GET_ALL_SWITCHES get_all_switches() {return new GET_ALL_SWITCHES();}
public GET_SWITCH_BY_ID get_switch_by_id() {return new GET_SWITCH_BY_ID();}
public MessageType build() {return id.build();}
public MessageTypeBuilder getBuilderBack() {return id;}
};

public REPLY() {id = new MessageTypeBuilder(); id.appendMatch8((byte) TOPIC_VAL__REPLY); }
public REPLY(MessageTypeBuilder preallocatedBuilder) {id = preallocatedBuilder; id.appendMatch8((byte) TOPIC_VAL__REPLY); }
public SWITCH_REGISTRY_MODULE switch_registry_module() {return new SWITCH_REGISTRY_MODULE();}
public MessageType build() {return id.build();}
public MessageTypeBuilder getBuilderBack() {return id;}
};

};
