//
// Created by Andre Kutzleb on 10/8/15.
//

#include <string>

#ifndef ZSDN_COMMONS_CONFIGS_H
#define ZSDN_COMMONS_CONFIGS_H

namespace zsdn {

    static constexpr const char* ZSDN_SWITCH_ADAPTER_PACKET_IN_MULTICAST_GROUPS = "ZSDN_SWITCH_ADAPTER_PACKET_IN_MULTICAST_GROUPS";
    static constexpr const char* ZSDN_SWITCH_ADAPTER_FLUSH_STREAM_AFTER_EVERY_MESSAGE = "ZSDN_SWITCH_ADAPTER_FLUSH_STREAM_AFTER_EVERY_MESSAGE";
    static constexpr const char* ZSDN_DEVICE_MODULE_PROTOCOLS_TO_USE = "ZSDN_DEVICE_MODULE_PROTOCOLS_TO_USE";
    static constexpr const char* ZSDN_SIMPLE_FORWARDING_MODULE_MULTICAST_GROUPS_FOR_INSTANCE_ID_ = "ZSDN_SIMPLE_FORWARDING_MODULE_MULTICAST_GROUPS_FOR_INSTANCE_ID_";
    static constexpr const char* ZSDN_SIMPLE_FORWARDING_MODULE_IGNORE_ETHERTYPES_FOR_INSTANCE_ID_ = "ZSDN_SIMPLE_FORWARDING_MODULE_IGNORE_ETHERTYPES_FOR_INSTANCE_ID_";
    static constexpr const char* ZSDN_FORWARDING_MODULE_MULTICAST_GROUPS_FOR_INSTANCE_ID_ = "ZSDN_FORWARDING_MODULE_MULTICAST_GROUPS_FOR_INSTANCE_ID_";
    static constexpr const char* ZSDN_FORWARDING_MODULE_IGNORE_ETHERTYPES_FOR_INSTANCE_ID_ = "ZSDN_FORWARDING_MODULE_IGNORE_ETHERTYPES_FOR_INSTANCE_ID_";
    static constexpr const char* ZSDN_SWITCH_ADAPTER_EXPERIMENTAL_FAST_TOPIC_GENERATION = "ZSDN_SWITCH_ADAPTER_EXPERIMENTAL_FAST_TOPIC_GENERATION";
    static constexpr const char* ZSDN_FORWARDING_MODULE_RULE_EXPIRE_THRESHOLD = "ZSDN_FORWARDING_MODULE_RULE_EXPIRE_THRESHOLD";

    static constexpr const char* ZSDN_LOGGING_MODULE_CASSANDRA_URL = "ZSDN_LOGGING_MODULE_CASSANDRA_URL";


} // namespace zsdn


#endif //ZSDN_COMMONS_CONFIGS_H
